url: "" # the base hostname & protocol for your site
baseurl: "/motherkaraoke.com" # the subpath of your site, e.g. /blog/

title: Mother Karaoke
description: A searchable index of karaoke songs for Mother in Atlanta, GA.
logo:
blurb: Check out the songs Mother Karaoke has to offer. We have a wide selection right at your fingertips. So what are you waiting for - get singing!

#social:
  #links:
    #- Uncomment and put social links here

exclude: ["_assets", "gulp", ".gitignore", "gulpfile.js", "package.json", "node_modules", "README.md", "Gemfile"]
keep_files: ["assets"]

# collections

# defaults

# gems
